FATAL: 2020/08/21 01:50:53.940929 main.go:28: Couldn't initialize database: ВАЖНО: база данных "amazingChatDB" не существует (SQLSTATE 3D000)
FATAL: 2020/08/21 10:20:33.906641 main.go:28: Couldn't initialize database: ОШИБКА: ошибка синтаксиса (примерное положение: ")") (SQLSTATE 42601)
FATAL: 2020/08/21 10:54:27.309250 main.go:28: Couldn't initialize database: ОШИБКА: удалить объект таблица chats нельзя, так как от него зависят другие объекты (SQLSTATE 2BP01)
ERROR: 2020/08/21 10:57:43.700207 chat.go:20: Error unmarshaling json: parse error: expected number near offset 32 of '1'
ERROR: 2020/08/21 10:58:01.464197 chat.go:68: Failed to insert to chat_users: <nil>
ERROR: 2020/08/21 10:58:01.464904 chat.go:59: Error commit: tx is closed
ERROR: 2020/08/21 10:58:01.465112 chat.go:30: tx is closed
ERROR: 2020/08/21 11:01:46.274779 chat.go:20: Error unmarshaling json: parse error: expected string near offset 30 of '1'
ERROR: 2020/08/21 11:02:14.867283 chat.go:74: Failed to insert to chat_users: <nil>
ERROR: 2020/08/21 11:02:14.867842 chat.go:60: Error commit: tx is closed
ERROR: 2020/08/21 11:02:14.867947 chat.go:30: tx is closed
ERROR: 2020/08/21 11:03:18.072555 chat.go:75: Failed to insert to chat_users: ОШИБКА: INSERT или UPDATE в таблице "chat_users" нарушает ограничение внешнего ключа "chat_users_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 11:03:18.074462 chat.go:30: ОШИБКА: INSERT или UPDATE в таблице "chat_users" нарушает ограничение внешнего ключа "chat_users_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 11:07:25.804140 chat.go:76: Failed to insert to chat_users: ОШИБКА: INSERT или UPDATE в таблице "chat_users" нарушает ограничение внешнего ключа "chat_users_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 11:07:25.804756 chat.go:30: this chat or one of users doesn't exist
ERROR: 2020/08/21 11:40:28.550506 message.go:20: Error unmarshaling json: parse error: expected number near offset 12 of '1'
ERROR: 2020/08/21 11:44:43.997109 message.go:36: Failed to scan row: ОШИБКА: INSERT или UPDATE в таблице "messages" нарушает ограничение внешнего ключа "messages_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 11:44:43.997922 message.go:26: ОШИБКА: INSERT или UPDATE в таблице "messages" нарушает ограничение внешнего ключа "messages_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 11:47:43.078851 message.go:37: Failed to scan row: ОШИБКА: INSERT или UPDATE в таблице "messages" нарушает ограничение внешнего ключа "messages_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 11:47:43.079429 message.go:26: this chat or user doesn't exist
ERROR: 2020/08/21 12:46:15.386576 user.go:45: Failed to scan row: can't scan into dest[0]: cannot assign 1 into *string
ERROR: 2020/08/21 12:46:15.387161 user.go:30: can't scan into dest[0]: cannot assign 1 into *string
ERROR: 2020/08/21 18:26:25.162654 chat.go:49: Failed to scan row: no rows in result set
ERROR: 2020/08/21 18:26:25.185263 message.go:31: no rows in result set
ERROR: 2020/08/21 18:26:46.904473 chat.go:49: Failed to scan row: no rows in result set
ERROR: 2020/08/21 18:26:46.904780 message.go:31: no rows in result set
ERROR: 2020/08/21 18:28:43.392343 chat.go:49: Failed to scan row: no rows in result set
ERROR: 2020/08/21 18:28:43.393142 message.go:31: this user is not in this chat
ERROR: 2020/08/21 18:29:33.816861 chat.go:49: Failed to scan row: no rows in result set
ERROR: 2020/08/21 18:29:33.819145 message.go:31: this user is not in this chat
ERROR: 2020/08/21 18:30:04.118987 chat.go:101: Failed to insert to chat_users: ОШИБКА: INSERT или UPDATE в таблице "chat_users" нарушает ограничение внешнего ключа "chat_users_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 18:31:43.678270 chat.go:101: Failed to insert to chat_users: ОШИБКА: INSERT или UPDATE в таблице "chat_users" нарушает ограничение внешнего ключа "chat_users_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 18:33:25.350806 chat.go:101: Failed to insert to chat_users: ОШИБКА: INSERT или UPDATE в таблице "chat_users" нарушает ограничение внешнего ключа "chat_users_userid_fkey" (SQLSTATE 23503)
ERROR: 2020/08/21 18:48:45.225371 chat.go:136: Failed to insert to chat_users: Scan received wrong number of arguments, got 5 but expected 4
ERROR: 2020/08/21 18:48:45.226255 chat.go:56: Scan received wrong number of arguments, got 5 but expected 4
ERROR: 2020/08/21 18:49:19.735037 chat.go:136: Failed to insert to chat_users: can't scan into dest[0]: cannot assign 4 into *string
ERROR: 2020/08/21 18:49:19.737081 chat.go:56: can't scan into dest[0]: cannot assign 4 into *string
ERROR: 2020/08/21 18:50:21.415374 chat.go:137: Failed to insert to chat_users: can't scan into dest[3]: cannot decode &pgtype.Int4Array{Elements:[]pgtype.Int4{pgtype.Int4{Int:1, Status:0x2}, pgtype.Int4{Int:2, Status:0x2}, pgtype.Int4{Int:3, Status:0x2}}, Dimensions:[]pgtype.ArrayDimension{pgtype.ArrayDimension{Length:3, LowerBound:1}}, Status:0x2} into *[]string
ERROR: 2020/08/21 18:50:21.415942 chat.go:56: can't scan into dest[3]: cannot decode &pgtype.Int4Array{Elements:[]pgtype.Int4{pgtype.Int4{Int:1, Status:0x2}, pgtype.Int4{Int:2, Status:0x2}, pgtype.Int4{Int:3, Status:0x2}}, Dimensions:[]pgtype.ArrayDimension{pgtype.ArrayDimension{Length:3, LowerBound:1}}, Status:0x2} into *[]string
